# ─────────────────────────────────────────────────────────────
#  render.yaml  —  configuration automatique pour Render
# ─────────────────────────────────────────────────────────────
services:
  - type: web
    name: edujeunes
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT eduplatform.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eduplatform.settings_render
      - key: SECRET_KEY
        generateValue: true          # Render génère une clé aléatoire automatiquement
      - key: PYTHON_VERSION
        value: "3.11.9"
